notification:
  slack:
    enabled: false
    success: 
    failure: 
  email:
    enabled: false
    to: 
    cc: 
    bcc: 
appUniqueName:
  appName: code-push-server
code_build:
  enabled: true
code_testing:
  enabled: true
  unit_test:
    enabled: false
  doc_gen:
    enabled: false
code_quality:
  sonar_test:
    enabled: false
artifact_backup:
  enabled: true
  
docker:
  linting:
    enabled: true
    report_path: ""
    report_name: "result.html"
  image_build:
    enabled: true
    docker_file_path: 
  image_scanning:
    enabled: false
    image_name: "docker-linter"
  publish_image:
    enabled: true
    registry:
      - name: "ecr"
        jenkins_credentials: ""
        admin_role: true

image_promotion:
  enabled: false
  registry:
  - name: "ecr"
    jenkins_credentials: ""
    admin_role: true
